### ISSUE TITLE
add lib/python symlink

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#122]
To work around the configure bug in CIAO 4.10, @nplee  added an extra sym link into the final ciao-4.10-contrib-1 tar file 

`contrib/lib/python -> contrib/lib/python3.5`

We should back-port this into the repro before we tag 4.10 on the master branch.

**Comment by DougBurke** [comment]
It should be going out in the 4.10.2 release, so I'm not about to hack the repro to address what we actually did. I'll leave this open until 4.10.2 is out.

**Comment by DougBurke** [comment]
Do we still need this for CIAO 4.11?

**Comment by kglotfelty** [comment]
I don't know.

This came about when we tried to install/upgrade CIAO in a terminal w/ ciao already setup.  Not sure if CM fixed what underlying cause.

**Comment by kglotfelty** [comment]
nothing definitive, just some random info

- we only have 1 python version in 4.11 so no 2.7 vs. 3.5 confusion.  But, the problem was that configure's pyver was "" (blank)
- ots/lib only has python3.5.  But
- ciao-4.11/lib has python3.5 and a python sym link to it.  This is the same as it was in 4.10.
- there are configure changes w.r.t. CIAO_PYTHON env. variable in 4.11

I tried to emulate the problem w/ 4.11 (install, source ciao setup, install again [add new pkg], source ciao setup w/ -o) and do not see the same problem (ie pyver="3.5") 

So we probably do not need it -- but if the contrib package stops working we know where to look.

**Comment by DougBurke** [comment]
I'd like to remove it, for "cleanliness" and to avoid potential tar issues with soft links, but is it too risky to do this at this time?

**Comment by kglotfelty** [comment]
it should be OK to remove.  Going back through release notes it was called out as being fixed.
