### ISSUE TITLE
deflare ahelp syntax line doesn't match parameter file

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#136]
The `<SYNTAX>` line in the help file should match the order in the parameter file

https://github.com/cxcsds/ciao-contrib/blob/0ecfe7743c3a5e0e7e8b2339a69cbc3c2975eea2/ciao-4.10/contrib/share/doc/xml/deflare.xml#L19-L23

vs.

https://github.com/cxcsds/ciao-contrib/blob/0ecfe7743c3a5e0e7e8b2339a69cbc3c2975eea2/ciao-4.10/contrib/param/deflare.par#L1-L3

IMO:  Unless there is need for it, I suggest removing the `<SYNTAX>` block entirely and letting
`ahelp` create the section automatically from the `<PARAMLIST>`

**Comment by DougBurke** [comment]
Is this the same issue as today's helpdesk ticket?

**Comment by kglotfelty** [comment]
Yes

Kenny
