### ISSUE TITLE
cda srservices going https://

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#138]
According to staff meeting notes and confirmed with archive team, the cda/srservices are moving to https://.

The timeframe for the change is with DS10.7 (2018-Oct ).

According to PZ, http:// will automatically be redirected to https://.   At some later date, the cda/csccli services will also go https, via a CAT release.

Due to the lack of SSL support in the version of Python packaged in CIAO 4.10, the following scripts will have new limits:

- [ ] `find_chandra_obsid` (when user supplies obs_id# instead of name|position)

When `csccli` goes secure the following will need updating

- [x]  `search_csc`
- [x]  `obsid_search_csc`

If we get SSL in CIAO 4.11 we can just change protocol. 

If not, we'll need to see about using `curl` hack that's used to access footprint services.

**Comment by kglotfelty** [comment]
CSC script updates are included in #131

**Comment by DougBurke** [comment]
`find_chandra_obsid` update in #148 (currently untested)

**Comment by DougBurke** [comment]
I'm claiming this is addressed with #131 and #148 merged.
