### ISSUE TITLE
plotting in CIAO 4.11 with matplotlib

### ISSUE THREAD

**Issue by DougBurke** [cxcsds/ciao-contrib#143]
For CIAO 4.11, should we

1. ignore the presence of matplotlib and rely on ChIPS for all our plotting
2. support matplotlib for plots created by Sherpa-related routines (I'm primarily thinking of `plot_rprof` and family, but there are others), and switch based on the selected plotting backend
3. support both everywhere

We could aim for 3, but start at 1 (i.e. add functionality after the release), or try and add some support before the 4.11 release.

# Issues with option 2

None of our Sherpa-related plotting commands make use of the Sherpa plotting abstraction, which would automatically support option 2. I haven't looked to see if the backend abstraction supports our needs (it may well not for some of the more-complex plots we do with `plot_rprof`, but that's a gut feeling).

# Issues with option 3

How do we chose the backend for something like the light-curve cleaning script (where some users would benefit from being able to run it in a "batch-only/no X11" mode which should be possible with matplotlib).

**Comment by kglotfelty** [comment]
Note:  Not sure if this is a separate issue -- but `dax` also uses `chips` plotting (and the `ds9` wrapper script launches `chipsServer` in the background).

**Comment by DougBurke** [comment]
Closing this as we've moved over to matplotlib now.
