### ISSUE TITLE
CIAO 4.11 remove specialized history propagation

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#150]
With the history mechanism in crates turned on in CIAO 4.11, we should remove any specialized code we have that's propagating history using `cxcdm`, eg in @nplee 's `ecf_calc` 

https://github.com/cxcsds/ciao-contrib/blob/0ecfe7743c3a5e0e7e8b2339a69cbc3c2975eea2/ciao-4.10/contrib/bin/ecf_calc#L66

I thought that Pete's tools (`detilt`, `dewiggle`, `symmertize`) were also doing something like this but I'm not seeing it right now.

**Comment by nplee** [comment]
addressed in latest revision of #235

**Comment by DougBurke** [comment]
I'm closing this now that #235 has fixed this for `ecf_calc`. It can be re-opened if there are other scripts which need to be updated.
