### ISSUE TITLE
blanksky no need to copy _AVG and _PNT in CIAO 4.11

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#156]
Note: in CIAO 4.11 we should no longer need to copy the `*_AVG` and `*_PNT` keywords by hand -- they should come for free with `reproject_events`

https://github.com/cxcsds/ciao-contrib/blob/6b7b3e751c6f0b6034c455827518bdb075e7e96b/ciao-4.10/contrib/bin/blanksky#L606

This code shouldn't hurt anything, just will (should!) be redundant.

**Comment by kglotfelty** [comment]
@nplee

**Comment by nplee** [comment]
addressed in #198
