### ISSUE TITLE
reg2tgmask open mode

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#170]
https://github.com/cxcsds/ciao-contrib/blob/fe1fe329ae4bc71da9f3e855a44dad5158c65f50/ciao-4.11/contrib/bin/reg2tgmask#L151

This should not be using `r+`, just `r`

**Comment by DougBurke** [comment]
This looks like something we could include in the next release (or is it more extensive than this one-letter change)?

**Comment by kglotfelty** [comment]
One letter should be it, I just haven’t had time to do it and test

Kenny
