### ISSUE TITLE
possible bug, sort order of interleaved mode obi in merge-obs

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#190]
https://github.com/cxcsds/ciao-contrib/blob/df6b0970dd7c221a643cfcacf0c4227433e081b5/ciao-4.11/contrib/lib/python3.5/site-packages/ciao_contrib/_tools/merging.py#L233

Sorry for the vague report ...

I sometimes see the `merge_obs` regression test report diffs in the interleaved mode tests.  It seems related to whether the files are sorted _e1_ then _e2_ or visa versa.  I'm not sure if the above snipet is the place where this sorting happens  or not.  That is both evt files will have the same MJD_OBS so I'm not sure if the sort order is unique.

Nominally this doesn't really matter -- except, the DTCOR in the e1 and e2 are very different, and so would affect the final LIVETIME and EXPOSURE time.  Note: this is somewhat related to #177 

FWIW: I'm seeing this on Ubuntu, and it, itself, does something funky with sort (the default sort order isn't the same as CentOS, I need to set LC_ALL=C to get defacto-standard sort order).  So I don't know if that also affects how python is sorting.

I'll post an example later -- I just wanted to capture now.

**Comment by DougBurke** [comment]
I'm going to assume #286 fixed this, but please feel free to re-open it if the regression tests still fail !
