### ISSUE TITLE
sherpa_contrib.marx fluxes

### ISSUE THREAD

**Issue by nplee** [cxcsds/ciao-contrib#194]
@hamogu Moritz: I was just testing out your sherpa_contrib.marx routines and I'm puzzled.  From what I understand, input spectra in MARX should have flux units of [photons/cm**2/s/keV] (https://space.mit.edu/cxc/marx/indetail/models.html#parameter-SpectrumFile) while ChaRT requires flux in [photons/cm**2/s].

Using the same absorbed power-law model and the sherpa_contrib.chart routines and sherpa_contrib.marx routines, the resulting spectrum appear to have the same fluxes, which I wouldn't have expected given the different unit requirements (see attached files).

[source_flux_chart.txt](https://github.com/cxcsds/ciao-contrib/files/2681188/source_flux_chart.txt)
[source_flux_marx.txt](https://github.com/cxcsds/ciao-contrib/files/2681189/source_flux_marx.txt)

Can you please confirm whether the documentation or module is problematic?

**Comment by hamogu** [comment]
I obviously forgot to follow-up on this, my vacation ended 6 weeks ago. Soon!
