### ISSUE TITLE
find_chandra_obsid on osx problem with SSL

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#196]
CIAO 4.11

As reported by @nplee and later by helpdesk ticket 21664,  when `libssl.1.0.0.dylib` is found on OSX (installed via homebrew, macports, or compiled into CIAO's ots/lib dir), find_chandra_obsid errors out:

```bash
% find_chandra_obsid 3C273 --tracebackdebug
# find_chandra_obsid (06 Nov 2018): ERROR <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:719)>
```
@DougBurke has #195 in the works to try to address it.

The final iteration we got down to

```bash
% find_chandra_obsid 645 --debug
# find_chandra_obsid (21 Dec 2018): ERROR 'str' object has no attribute 'decode'


##### Traceback:

Traceback (most recent call last):
  File "/Applications/ciao-4.11/contrib/lib/python3.5/site-packages/ciao_contrib/logger_wrapper.py", line 531, in new_fn
    return fn(*args, **kw)
  File "/Applications/ciao-4.11/contrib/bin/find_chandra_obsid", line 612, in fco
    run_fco(opts)
  File "/Applications/ciao-4.11/contrib/bin/find_chandra_obsid", line 562, in run_fco
    pos = find_obsid_position(name)
  File "/Applications/ciao-4.11/contrib/bin/find_chandra_obsid", line 516, in find_obsid_position
    ans = retrieve_url(url).read().decode('utf8')
AttributeError: 'str' object has no attribute 'decode'
```

and it looks like removing the `.decode('utf8')` fixes that problem.

**Comment by DougBurke** [comment]
I've squashed down #195 to a single commit, but I can't test this so don't know whether it's good to include or not.

**Comment by DougBurke** [comment]
I'm going to close this since the code has been merged and I don't think we've had anymore helpdesk tickets about it, but please re-open if that's not the case.
