### ISSUE TITLE
blanksky should be using PNT instead of NOM

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#214]
We should be using the `PNT` keywords here to identify the aimpoint chip:

https://github.com/cxcsds/ciao-contrib/blob/d5598fd418b9d5c04798fb71608999d01c6794c0/ciao-4.11/contrib/bin/blanksky#L493-L502

instead of using the `NOM` value.  

 It won't matter most of the time since they are generally close (mostly equal) but in cases where the data have been reprojected to a significantly different tangent point, then we could get wrong aimpoint.

**Comment by DougBurke** [comment]
Closed by #215
