### ISSUE TITLE
srcflux problem with photflux

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#217]
There is a mistake in the equation used to compute the net photon flux in the `srcflux` script

https://github.com/cxcsds/ciao-contrib/blob/d5598fd418b9d5c04798fb71608999d01c6794c0/ciao-4.11/contrib/bin/srcflux#L1379

    S = a*F + N
    B = b*F + r*N

where S = counts in src region, B = counts in bkg region, a = psf frac in src, b = fraction of src psf in bkg, F = source flux, N = background, r = aperature area  scale.

Solve for N.

    N = (B - b*F)/r

and plug that in to find F.

    S = a*F + (B-b*F)/r
    r*S = r*a*F + B - b*F
    r*S-B = F*(r*a-b)
    F = r*S-B / ( r*a-b)

In the current code, the denominator is incorrect `r*(a-b)` 

For `psfmethod=ideal|quick`, `b=0` so the error doesn't show up.  However, for
`psfmethod=arfcorr|file|marx`, then we are computing the wrong PSF scaling fraction for the background.

This only affects the `net_photon_flux` and it's uncertainties.

**Comment by DougBurke** [comment]
For typical `r`, `a`, and `b`, values, what is the difference between `r * (a - b)` and `r * a - b`? ie can we say to users that the `net_photon_fluxes` are typically ~ x% under/overestimated (with the understanding that if users have chosen "atypical" apertues then all bets are off)?

**Comment by kglotfelty** [comment]
So in `srcflux`, `r = bkg_area / src_area`, so will be > 1 (typically).

The background radius typically|default is 3 times the src radius, so r ~= 8.  `a` and `b` are tricky.  `a` is typically around 90%, b might be around 5% depending on energy/off-axis-angle.   But in the run I was doing `a=0.88` and `b=0.11`.

It won't be orders of magnitude unless `a` is really small.

**Comment by DougBurke** [comment]
So 5 - 15% is probably a reasonable value to quote. If my mental math is working then the current code is over-estimating the `net_photon_flux` by this amount.

**Comment by kglotfelty** [comment]
That sounded kinda low ... I double checked and the default background radius is 5, so the 'r' factor will be ~24; doesn't make a big diff .. but something in that range

**Comment by kglotfelty** [comment]
Unfortunately, I also see that this same error is in the model-independent, `eff2evt`, fluxes too.  The same percent diffs (overestimates).
