### ISSUE TITLE
make_psf_asymmetry_region NOM vs PNT

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#23]
(Posting here from ciaoscript email last year)

Just a quick note ... make_psf_asymmetry_region is using the ROLL_NOM keyword instead of the ROLL_PNT keyword.  _PNT should be used, if it exists.

[boiler-plate : they are diff for multi-obi and reprojected/astrometric-corrected datasets; however PNT is purposefully dropped from L2 file, and is '0' in the asol files.]

Also it's using hard-code plate scales; I don't expect they'll change, but would be better long-term to get via pixlib or the caldb file.

**Comment by DougBurke** [comment]
Is there a simple magic caldb incantation to get the pix scale? Or do you have to reconstruct it from a bunch of data? We don't really have any instructions on doing something like this (that I could find).

**Comment by kglotfelty** [comment]
I'm not remember the details of the comment specifically but we can use pixlib to get arcsec/pixel:

```python
>>> from pixlib import *
>>> p = Pixlib()
>>> p.detector="HRC-I"
>>> print(p.fp_scale)
0.1318
>>> p.detector="ACIS"
>>> print(p.fp_scale)
0.492
```

Note:  HRC must be either HRC-I or HRC-S ... ACIS is just ACIS.

**Comment by DougBurke** [comment]
Ta for the pixlib tip

**Comment by DougBurke** [comment]
Hmmm. The script currently uses a plate scale of 0.13175 for HRC. If I change to the above then the results will change slightly. Is 0.1318 the "correct" answer or has it been rounded? I also couldn't tell you where I got the 0.13175 value from. It is only a ~ 0.04% change so not going to significantly affect the result here, but thought I'd mention it.

**Comment by nplee** [comment]
starting in the cycle 19 POG, the HRC information table
http://cxc.cfa.harvard.edu/proposer/POG/html/chap7.html#tb:hrc-par

started giving a "pixel size (default binning size" of 0.1318 arcsec/pix in addition to the "pixel size (electronic readout)" that we're familiar with of 0.13175 arcsec/pix...

**Comment by kglotfelty** [comment]
0.1318 is what's stored in the CALDB, so that's what's used to in the coord calcs to go from chip to sky coordinates.

```bash
% dmlist $CALDB/data/chandra/default/sky/telD1999-07-23skyN0001.fits data,clean,all | grep HRC
 FP-2.0                               0.1250                    16384.50     16384.50                 1 -1 HRC (old)             
 FP-2.1                              0.13180                    16384.50     16384.50                 1 -1 HRC-I                 
 FP-2.2                              0.13180                    23000.50     23000.50                 1 -1 HRC-S (old)           
 FP-2.3                              0.13180                    32768.50     32768.50                 1 -1 HRC-S                 
 FP-4.0                               0.1250                    16384.50     16384.50                  1 1 XRCF HRC (old)        
 FP-4.1                               0.1250                    16384.50     16384.50                -1 -1 XRCF HRC-I            
 FP-4.2                               0.1290                    16384.50     16384.50                -1 -1 XRCF HRC-I            
 FP-4.3                               0.1290                    32768.50      4196.50                -1 -1 XRCF HRC-S           
```
