### ISSUE TITLE
coords.chandra _PNT keywords

### ISSUE THREAD

**Issue by DougBurke** [cxcsds/ciao-contrib#236]
I just tried `coords.chandra.sky_to_chandra` on a l3 file (I'm updating the ahelp file to remove chips) and noticed that it failed

```
chips In [5]: sky_to_chandra(keywords, 4096.5, 4096.5)
KeyError: 'RA_PNT'
```

/pool14/dburke/sens3.fits is an example

Is this because the routines arent' designed for L3 products (e.g. merged), or because the module hasn't been updated for recent-ish changes, or some other nefarious reason?

**Comment by DougBurke** [comment]
I've edited the title since I see the same thing with a L2 product

**Comment by kglotfelty** [comment]
which L2 file?  

The PNTs should be there except for the multi-obi obsids.

**Comment by DougBurke** [comment]
Sorry, I was imprecise. By L2 I meant a file created from L2. It was actually an output from `flux_obs` but I now can't remember if it was a merged file or from a single obsid.

**Comment by kglotfelty** [comment]
Merged products are invalid since the default merging rules are to omit those keys.  I also see SIM_* and D*_AVG are missing.

**Comment by DougBurke** [comment]
It was to a merged file.

**Comment by DougBurke** [comment]
Is it easy to come up with a list of required keywords?

**Comment by kglotfelty** [comment]
It's in one of the internal doc strings but not a particularly useful place for end-users

```python
    Input is a dictionary of keyword values that must contain
    the following values:
        
        INSTRUME
        DETNAM
        RA_NOM
        DEC_NOM
        RA_PNT
        DEC_PNT
        ROLL_PNT
        SIM_X
        SIM_Y
        SIM_Z
        DY_AVG
        DZ_AVG
        DTH_AVG
```

**Comment by DougBurke** [comment]
I'm closing this now that #249 has been merged.
