### ISSUE TITLE
download_obsid_caldb outdir with trailing "/" fails

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#24]
The `download_obsid_caldb` tool fails when the output directory parameter contains a trailing "/" 

```bash
$ download_obsid_caldb foo_evt.fits outdir=somedir/
...
Retrieving CALDB data files
    Filename:                               0------------------1
    telD1999-07-23aimptsN0002.fits          
# download_obsid_caldb (18 Nov 2016): ERROR 550 //pub/arcftp/ChandraCalDB/somedir/data/chandra/default/aimpts: No such file or directory
```

When the script is mapping the CALDB directory name onto the output directory, it's using a `.replace()` which is assuming the `outdir` does not contain the trailing `/`  so it adds it:

```python
zz = hasdir.replace( outdir+"/", "", 1 ) 
```
since this leads to a double `//` then the replace is a no-op and the wrong path is used.

Rather than deal w/ trying to guess when the path is or isn't there, it's easiest to just strip off the trailing path if it's there:

```python
    outdir = pars["outdir"].rstrip("/")   
```

**Comment by DougBurke** [comment]
Fixed by #28
