### ISSUE TITLE
fullgarf change check for ASCDS_BIN deprecation

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#250]
In the `conda` builds, the `$ASCDS_BIN` environment variable is no longer being set.  We'll need to change `fullgarf`  to check either `$ASCDS_INSTALL` or `$ASCDS_INSTALL/bin` 

https://github.com/cxcsds/ciao-contrib/blob/a6cd76a1c17838264b256f64be9422c664f47be4/ciao-4.11/contrib/bin/fullgarf#L597-L613

**Comment by DougBurke** [comment]
Should we bite the bullet and make this a python script?
