### ISSUE TITLE
dax fit stat,  background subtract

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#263]
From @anetasie 

> Selection of 'cstat','cash', or 'wstat' in DAX statistics does not result in fit, because the data cannot be background subtracted. Perhaps you can update DAX to use unsubtracted data if these statistics are selected. Now, I just went to separate Sherpa session and restarted the fit.

**Comment by DougBurke** [comment]
Just a note about wstat - it is not at all obvious how best to plot data + model when this is selected.

**Comment by kglotfelty** [comment]
The background `subtract` part of this was resolved in 4.11.5.
