### ISSUE TITLE
combine_grating_spectra keyword merging

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#273]
Some keywords in the combine spectra should be updated or removed.  These are being copied from one of the input files -- which file is random based on python's dictionary ordering.

Things like

- [ ] `TG_M`
- [ ] `SPEC_NUM`

**Comment by DougBurke** [comment]
Is this a "nice to have" change or a "causing problems downstream" kind of issue?

**Comment by kglotfelty** [comment]
It's not causing any downstream problems.  Just causing diffs in py37 vs. py35 regression testing.  So nice to have.

**Comment by DougBurke** [comment]
Ta for the clarification.
