### ISSUE TITLE
dax fill task error checking

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#285]
This check in `dax` is ugly and fragile.

https://github.com/cxcsds/ciao-contrib/blob/4a3a5a1858462cd6369f00bc90abcc0250221466/ciao-4.11/contrib/bin/ds9_fill.sh#L62

I'm not really sure the exit status is really getting set by `grep` .  At the very least `grep` ends up printing an 

`Input Error`

message (since FITS file has binary data).

Would be much more simple if `dmfilth` just set correct exit status.

**Comment by DougBurke** [comment]
Do we have `dmfilth` on our list-of-tools-that-we've-reported-as-not-setting-the-exit-status?

**Comment by kglotfelty** [comment]
It's in my bug list -- but who looks at that :)

**Comment by DougBurke** [comment]
Not me, otherwise I wouldn't have needed to ask ...
