### ISSUE TITLE
ecf_calc does not work with python 3.5: tabs/spaces and xrange

### ISSUE THREAD

**Issue by DougBurke** [cxcsds/ciao-contrib#29]
With CIAO 4.9/python 3.5, I get:

    % ecf_calc
      File "/data/dburke2/sds/py35/ciao-4.9/contrib/bin/ecf_calc", line 418
        pause()
              ^
    TabError: inconsistent use of tabs and spaces in indentation

It also contains an `xrange` call:

    % grep xrange /data/dburke2/sds/py35/ciao-4.9/contrib/bin/ecf_calc
            for ii in xrange( 1, cxcdm.dmBlockGetNoKeys(tab)+1 ):

**Comment by nplee** [comment]
fixed this issue; using "range" in lieu of "xrange" works for both P2 and P3 and fixed the various indentation issues
