### ISSUE TITLE
lc_clean plots with matplotlib 3.x.x

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#293]
Just putting this here so it's not forgotten --

With matplotlib 3 , the lc_clean plots are coming out odd:  squashed with lots of white space between them:

![deflare2](https://user-images.githubusercontent.com/6662179/68126698-585c0380-fee2-11e9-81f7-19f932db3db5.png)

when I'd looked at this earlier I was seeing warnings like:

    /data/lenin2/Test/CIAO4.12/Conda/miniconda/envs/ciao-4.12b1/lib/python3.5/site-packages/matplotlib/tight_layout.py:209: UserWarning: tight_layout cannot make axes height small enough to accommodate all axes decorations
      warnings.warn('tight_layout cannot make axes height small enough '

This was only happening in the conda build but now in 4.12b2 where we've updated classic ciao it's showing up there too.

**Comment by DougBurke** [comment]
Can this be closed now @nplee?

**Comment by nplee** [comment]
yep
