### ISSUE TITLE
deflare matplotlib deprecation warning

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#295]
In the python 3.7 edition of conda ciao 4.12 `deflare` is printing the following deprecation warning:

> INSTALL/bin/deflare:172: MatplotlibDeprecationWarning: 
> The frameon kwarg was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use facecolor instead.
>   plt.savefig(oplot, format=format, frameon=True)
> INSTALL/bin/deflare:172: UserWarning: Tight layout not applied. tight_layout cannot make axes height small enough to accommodate all axes decorations
>   plt.savefig(oplot, format=format, frameon=True)
146a156,160

**Comment by DougBurke** [comment]
Can this be closed now @nplee?
