### ISSUE TITLE
merge_obs numpy 1.15.x warning

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#296]
There is a new numpy warning in the conda-ciao-py3.7 edition from merge_obs

> INSTALL/lib/python3.7/site-packages/ciao_contrib/_tools/merging.py:2592: RuntimeWarning: divide by zero encountered in true_divide
>   newvals = numerator / denominator

in the wavdetect_merged thread. I'm assuming we just need to add a `divide='ignore'` to `np.seterr()` ?

```python
  2590      res = np.seterr(invalid='ignore')
  2591      try:
  2592          newvals = numerator / denominator
  2593          newvals = newvals.astype(np.float32)
  2594      finally:
  2595          np.seterr(**res)
```

FWIW:

    ciaot: python -c 'import numpy;print(numpy.__version__)'
    1.12.1

    conda: python -c 'import numpy;print(numpy.__version__)'
    1.15.2

**Comment by DougBurke** [comment]
For reference, this needs `psfecf=0.35 psfmerge=expmap` set (or some value for `psfecf`) to trigger.
