### ISSUE TITLE
assumption of paths with conda builds: ASCDS_CONTRIB

### ISSUE THREAD

**Issue by DougBurke** [cxcsds/ciao-contrib#304]
`ciao_contrib/_tools/run.py` contains the following, which is going to fail in conda builds when there's no `$ASCDS_CONTRIB` environment variable.

```
    v3("Looking for the lookup table for: " + toolname)
    for f in [dirpath + "/../data/" + fname,
              dirpath + "/" + fname,
              os.getenv("ASCDS_CONTRIB") + "/data/" + fname,
              os.getenv("ASCDS_CALIB") + "/dmmerge_header_lookup.txt"]:

        f = os.path.normpath(f)
        v3("Looking for: " + f)
        if os.path.exists(f):
            return f
```

**Comment by DougBurke** [comment]
I'm a bit-more concerned about the parameter files:

```
% grep -l ASCDS_CONTRIB param/*
param/dewiggle.par
param/imagej_lut.par
param/symmetrize.par
param/ximage_lut.par
```

e.g.

```
% grep ASCDS_CONTRIB param/dewiggle.par 
wfile,f,h,"${ASCDS_CONTRIB}/data/wigglecorrection.dat",,,"Wiggle correction file"
```

@kglotfelty - did we ask for ASCDS_CONTRIB to be retained in the conda environment or not?

**Comment by kglotfelty** [comment]
Note: `$ASCDS_CONTRIB` missing causes other problems (`dax` and Pete's `detilt`, `dewiggle`, and|or `symmertrize` )

**Comment by kglotfelty** [comment]
It is set -- but only by the activate script that is installed with conda

**Comment by DougBurke** [comment]
It doesn't seem to be getting set for me at work - but maybe this is
because I'm having to say 'source activate blahblah' rather than 'conda
activate blahblah' because of hysterical shell-raisins.

**Comment by kglotfelty** [comment]
Sorry, meant you have to conda install contrib to install the activate script that sets it

Kenny

**Comment by DougBurke** [comment]
I can see why, but that's annoying for my use case ;-)

Doug

**Comment by kglotfelty** [comment]
Me too, re: CALDB 

Kenny
