### ISSUE TITLE
download_chandra_obsid new data products

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#332]
There will be two new sets of data products once all of Repro5 gets implemented (so maybe this should be two issues)

- [ ] A new single per-obi aspect solution for the boresight offset changes 
- [ ] New grating response files.

Not sure where (primary/, secondary/) these will be ; if they'll be implemented together (same DS release) ; or file naming.

**Comment by DougBurke** [comment]
In #347 I'e added support for _arf and _rmf filetypes, which will hopefully support the grating response files.

I believe the new aspect solution has the same name (but different directory) as the old one (more pertinently, both contain the string `_asol`). If so then I think we should be fine. Will we have data sets with both old and new format asol files (i.e. does the new file add to the dataset, or replace what used to be generated)?

**Comment by kglotfelty** [comment]
According to Joe, according to Mike, the new asol file replaces the old
one.  The current time-based asol file , pcadf<<time>>_asol1.fits will only
be available as a supporting product (so only via chaser)

**Comment by DougBurke** [comment]
The new files are called pcadf<obsid>_asol1.fits (or some variant)? Or did I mis-remember this?

**Comment by kglotfelty** [comment]
Yes.  The new files have obsid_obinum in the filename; the old files have
the tstart.

**Comment by DougBurke** [comment]
I've checked the new code works with asol files. I'm not sure we have any grating responses we can test against yet?

**Comment by kglotfelty** [comment]
Nothing public that I can find.  The only thing I see is that the `responses` directory is always there whether grating or not.  (doesn't break anything [now], just not a fan of empty dirs).

**Comment by DougBurke** [comment]
We'll leave this open then until we can check it works with grating responses.

**Comment by kglotfelty** [comment]
Confirmed -- works with grating response files, obsid `23206`
