### ISSUE TITLE
update skyfov method with new asol file?

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#346]
When the new obi-asol files are released, we can|could|should think about updating the contrib scripts to use the new `method=convexhull` algorithm in `skyfov`.

A quick grep looks like

- [x] `chandra_repro`
- [x] `srcflux`
- [ ] `ciao_contrb._tools.fileio.py`

We can key off the `CONTENT` keyword

```bash
% dmkeypar 13819/primary/pcadf13819_000N001_asol1.fits content echo+
ASPSOLOBI

% dmkeypar 13819/secondary/pcadf444003563N001_asol1.fits content echo+
ASPSOL
```
Eg something like:

```python
choices={ 'ASPSOLOBI' : 'convexhull' , 'ASPSOL' : 'minmax' }
```

The advantage is that the FOV will, in general, be tighter (never larger).    Since we can key off values in data products we can make this change independent of new asol files in the wild.

Since there are more|variable number of points in the polygons not sure if that affects anything anywhere else?

**Comment by DougBurke** [comment]
I think I use the skyfov to determine sky ranges for `fluximage`/`merge_obs`/..., so there may be some changes to the output data, but I would hope it doesn't materially change the data.

**Comment by DougBurke** [comment]
With #358 having been merged I think we can close this now.

**Comment by kglotfelty** [comment]
Correct.
