### ISSUE TITLE
dax ciao4.13 w/ ds9 8.2

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#383]
ds9 8.2 that will be released with ciao-4.13 will have new analysis menu option to specify parameter as a file to open|save.

dax will want to replace the psfmap and exposure map parameters (currently on dax_guis branch) with the new `open` type.

This is just a reminder.

**Comment by kglotfelty** [comment]
Will also want to implement new grating coords task w/ `dmcoords` update to ask what energy is imaged at this location.

**Comment by DougBurke** [comment]
I assume the "new grating coords" task was included in #380, but there are still DAX changes we can now merge?

**Comment by kglotfelty** [comment]
The gratings thing is different.  w/ #380 we can go from energy to sky position.  With ciao 4.13, we can finally go from sky to energy ; so a new task.

No; no dax updates are done for 4.13 yet.
