### ISSUE TITLE
RFE: merge_obs create a merged FOV

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#389]
Just a place holder for now ... but working w/ AF on multi-obsid `srcflux`, the issue of wanting a merged FOV file to go along with the merged images came up.

Not sure if this is just using the `dmmakereg` with `[cols ra,dec,stuff]`, or if we'd want to go w/ re-running `skyfov` using new|merged tangent point to get meaningful physical coords.

**Comment by DougBurke** [comment]
So take each of the reprojected event files and create a new FOV file, and then merge them together?

As an aside, for the CSC I did write code that would take a bunch of overlapping FOV files and then combine them into a set of polygons (include and exclude), but this requires the University of Manchester polygon library (gpc?) which I think is available via pip but not something we'd want to distribute.

**Comment by kglotfelty** [comment]
That's what I was thinking.  

w.r.t. 'merge them' -- dmmerge won't work (in general) due to diff in number of points per poly.  But we can use the region module to combine them

```python
>>> combo=CXCRegion("obs1.fov")+CXCRegion("obs2.fov")+...
>>> combo.write("merge.fov",fits=True) 
```
we loose the `ccd_id` column but we don't loose precision (and end up with even more 0-length polygon warnings).

**Comment by DougBurke** [comment]
So #528 handles this but *only* for the users calling `reproject_obs` and then `flux_obs`. It's not immediately obvious where to stick this into the `merge_obs` pipeline (as we don't create any of the other ancillary files like asol/mask). The files are temporarily there but we delete them (or never make them obvious to the user).
