### ISSUE TITLE
lightcurve clean report mean and sigma

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#398]
Base on HD ticket 22909 , w/ obsid 17542 

using `deflare` with `clean`, it raises this exception

https://github.com/cxcsds/ciao-contrib/blob/27348431ec4d5520b9eec2cd35a249f7e43952c5/lightcurves.py#L950

it would be good if we included the mean and sigma that were computed here so users get a sense of what values are and why this exception is thrown.

**Comment by DougBurke** [comment]
Closed by #401 (I assume)
