### ISSUE TITLE
specextract py3.8 literal comparison test

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#400]
https://github.com/cxcsds/ciao-contrib/blob/27348431ec4d5520b9eec2cd35a249f7e43952c5/bin/specextract#L2155-L2156

In python 3.8, these `is not True` are throwing a warning

    INSTALL/bin/specextract:0: SyntaxWarning: "is not" with a literal. Did you mean "!="?
    INSTALL/bin/specextract:0: SyntaxWarning: "is not" with a literal. Did you mean "!="?

Looking at the lines, I don't think they logic is needed at all, and it should just be 

```python
blanksky = [kw for kw in blanksky if kw != "-99"]
mm_blanksky = [kw for kw in mm_blanksky if kw != "-99"] 
```

:question:

**Comment by DougBurke** [comment]
Yeah, that looks like a lot of work for no gain!
