### ISSUE TITLE
srcflux ahelp missing psfmethod=marx

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#414]
https://github.com/cxcsds/ciao-contrib/blob/a8c3e223ba05bd1f53ddea36729d2d13e4f0e9c8/share/doc/xml/srcflux.xml#L822

**Comment by DougBurke** [comment]
This is now fixed in #387, right?

**Comment by kglotfelty** [comment]
yes. added to mesg
