### ISSUE TITLE
dax plots no longer match sherpa in 4.13

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#427]
dax will need to update its plots to match what sherpa is creating in 4.13

- [ ] step plots, so need to get bin edges

the delchi also has x-error bars for bin width (not new in 4.13).

**Comment by DougBurke** [comment]
The lot objects have all the data you need, it's just creating the lines that is a bit annoying.

**Comment by kglotfelty** [comment]
it looks like the pha plot objects are different from the radial profile (no .xlo).

**Comment by DougBurke** [comment]
That's expected. The "integrated data" plot objects have .xlo, .xhi (and .x) whereas the "not-integrated" just have .x.

"integrated" == Data1DInt, DataPHA
"not-integrated" == everything else
