### ISSUE TITLE
dax spectral fit enhancements

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#443]
From @anetasie 

I was just running Sherpa fit using DAX. Is there an option for confidence on the fit parameters?
It would be nice to have it.

In the additional model options it would be good to have also absorption models which allows for additional intrinsic absorption component and in this case one does not need to check the colden, but use default settings, with redshift option which could be modified.
xszwabs, xszphabs, xsztbabs

**Comment by kglotfelty** [comment]
The calc*flux need the energy range passed in (not just on noticed range).

https://github.com/cxcsds/ciao-contrib/blob/82de62479d5615ace53b47f459ccf94fb625f415/bin/ds9_specfit.sh#L301-L302

**Comment by DougBurke** [comment]
I think - but would need to check as the documentation isn't clear about what `lo=hi=None` means - but if you don't give an energy range to these calls then you get the instrument response (ie not the noticed range). Yup, for this fit we have a noticed range of 0.5-7 but when no arguments are given you get "the full" range (as shown by it being larger than when you give 0.5-7 expicitly)

```
sherpa In [5]: calc_energy_flux()
Out[5]: 1.0463307014523392e-12

sherpa In [6]: calc_energy_flux(lo=0.5, hi=7)
Out[6]: 7.782346951689922e-13

sherpa In [7]: ignore(None, 2)

sherpa In [8]: ignore(3, None)

sherpa In [9]: calc_energy_flux()
Out[9]: 1.0463307014523392e-12
```

**Comment by DougBurke** [comment]
As we now give the limits in #446 - https://github.com/cxcsds/ciao-contrib/pull/446/commits/892e2141ebd1fdc1eb5af69fe927081c0d61217b - this is more for the text explainig what's changed.
