### ISSUE TITLE
future: CSC2 updates

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#45]
Just a place holder for now, but need to keep in mind that with release 2 of the catalog (and cscview updates) we'll need to rework the `search_csc` and `obsid_search_csc` scripts.

    My expectation is somewhat substantial changes given the extra detect-stack 
    layer of properties & linkages.  I doubt the single existing `catalog` parameter 
    will be sufficient to capture the changes.

**Comment by DougBurke** [comment]
I think we can close this now, can't we?

**Comment by kglotfelty** [comment]
Yes w/ caveat

There is still an open question about how sensitivity info can/will be accessible but we can spawn that into a separate issue.

**Comment by kglotfelty** [comment]
This is 4.10.3; the only remaining issues are in #162.
