### ISSUE TITLE
simulate_psf tstart

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#454]
From @nplee  helpdesk ticket 23194

When simulate_psf was written, at least of what we understood from the original documentation, the TSTART parameter in MARX required to be in *decimal years*, but the TSTART values in the various files are in *seconds* of Chandra mission time.  So simulate_psf would use the "prop_dates" proposal tool to convert Chandra mission time to decimal years, but the tool has a precision of only a hundredth of a year... or ~3.5 days. This means that the different TSTART values in the event file and aspect solution will result in rounding the decimal year to the same value:

```bash
unix% prop_dates p0 from TIME to JEPOCH eval `dmkeypar acisf10753_repro_evt2.fits TSTART echo+`
J2009.41

unix% prop_dates p0 from TIME to JEPOCH eval `dmkeypar pcadf10753_repro_asol1.fits TSTART echo+`
J2009.41
```
The exact year 2009.41 would then translate to a mission time of :

```bash
unix% prop_dates p0 from JEPOCH to TIME eval J2009.41
360072219
```

and probably due to compiling and machine precision differences across software and platforms, MARX translates the decimal year value to a slightly different Chandra mission time of:

```bash
unix% dmkeypar psf/sim_projrays.fits TSTART echo+
360072216.0
```

**Comment by DougBurke** [comment]
Is there a software change we can make here, or is this just a "gotcha" for the documentation?

**Comment by kglotfelty** [comment]
There is a change; I've got it on one of my branches, but the odd thing is that it only changes the TIME values in the marx output.  I'm not sure how that can possibly be the case that we change the time values, but the chip|sky|det coordinates (and thereby the final PSF image) are the same.   I'm guessing MARX is really doing something cosmetic (eg adding "a" time column just to have it) or else something else is amiss.

Upshot -- not ready and don't want to bug folks until after deadline.

**Comment by DougBurke** [comment]
Ta - just wanting to understand what may be coming down the pike,
