### ISSUE TITLE
should specextract check the energy range for energy_wmap to ensure there's data?

### ISSUE THREAD

**Issue by DougBurke** [cxcsds/ciao-contrib#456]
From the helpdesk, we find specextract will error out in an unhelpful manner if the energy_wmap range contains no data. Would it make sense to add a check to catch this case? Technically we might want to error out if the number of counts is smaller than some magic count, but it's hard to come up with this limit.

**Comment by nplee** [comment]
I've added a check for the zero-counts case for the next release.  Haven't thought much about the mathemagical limit route yet.

**Comment by nplee** [comment]
addressed in #469
