### ISSUE TITLE
download_chandra_obsid differentiate vv and vvref files

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#463]
As per today's helpdesk ticket, the vvref2.pdf is often the largest file for an obsid; yet it contains little of interest to most users beyond what is in the much smaller vv2.pdf file. 

Most users just want the comments -- I wish there was a public API for these.  But since not, it would be nice if download_chandra_obsid would treat these two files as different file types: `vv` and `vvref`

**Comment by DougBurke** [comment]
So I can think of several approaches

1. not useful

  `vv` also downloads the `vvref` version (essentially the same as now)

2. probably what we go out with

  `vv` and `vvref` are completely separate

3. not worth it

  `vvref` subsumes `vv` (i.e. it means get both).

**Comment by kglotfelty** [comment]
I'd vote for :two:

**Comment by DougBurke** [comment]
Gah, trickier than I'd hoped. It's easy to add vvref as an option, but I think we also want the default behavior to ignore the vvref2 files (that is, you only get them if you explicitly ask for them). Previously the default has been to download everything, which requires some re-jigging.
