### ISSUE TITLE
install_marx add symlink

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#471]
JCM:

> If we put a soft link in `$ASCDS_INSTALL/marx -> marx-5.5.1`, then I could have an alias 

```bash
alias setmarx='source ${ASCDS_INSTALL}/marx/setup_marx.csh'
```
> that wouldn't need to be changed ever (i.e. when the marx version changes).

KJG: need to support updates (so del and re-link if new version is installed).

**Comment by DougBurke** [comment]
If we were a bit-more "FHS" adjacent we might want to put it in share/ or some other location, but I'm not sure it's worth it.

**Comment by kglotfelty** [comment]
We could also install into ots/ (and then the setup script wouldn't need to set PATH).  But that requires a single version (which isn't really a big deal, IMO).
