### ISSUE TITLE
review runtool for dmgti like shell scripts

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#49]
As per the helpdesk ticket discussion "CXC HD Ticket: 'axbary' Python script temporary input file issue", the list of tools that are shell-scripts that don't support the `@@` parameter interface syntax needs to be reviewed/updated.   The suspects include:

- `axbary`
- __`dmgti`__
- `evalpos`
- __`fullgarf `__
- `mean_energy_map`
- `pileup_map`
- `tgdetect`
- `wavdetect`

**Comment by DougBurke** [comment]
Hmmm, I was going to just say all shell scripts are problems, but `evalpos` is doing something cute (see below) which looks like it potentially could work (it depends on how `pquery` works)

```
MYNAME=evalpos
for pp in `pdump ${MYNAME} | cut -d= -f1 | grep -v '^# EOF'` 
do
  eval ${pp}=`echo $pp | pquery ${MYNAME} - "$@" | sed 's/[ ()\[]/\\\&/g'`
done
```

Let's check:

```
% cat myevalpos.par
infile,f,a,"bob.fits",,,"Input image files"
ra,s,a,"haha",,,"Input right ascension"
dec,s,a,"hoho",,,"Input declination"
output,r,l,"",,,"Output value (last in stack)"
tmpdir,f,h,"${ASCDS_WORK_PATH}",,,"Directory for temp. files"
verbose,i,h,0,0,5,"Chatter level"
mode,s,h,"ql",,,
% pquery evalpos infile infile=2323.sdfsdf
2323.sdfsdf
% pquery evalpos infile @@myevalpos.par mode=h
bob.fits
% echo ra | pquery evalpos - @@myevalpos.par mode=h
haha
```

Note that without `mode=h` (presumably it can be set in the `.par` file) then you get queried for the answer, with it defaulting to the value from the parameter file.

So it looks like I can't just dismiss the shell scripts! Can we get them all to use this trick?

**Comment by kglotfelty** [comment]
> Can we get them all to use this trick?

Probably yes ... on what time scale is really anyone's guess.  I don't remember just how robust the `sed` post-processing is but hopefully with enough quotes that really is sufficient.



I'm not sure if this is a separate tangent, but then `evalpos` does suffer from other parameter race-conditions:

```bash
  # Convert ra/dec to x/y
  #
  punlearn dmcoords
  dmcoords "${sen}" asol=none op=cel ra="${ra}" dec="${dec}"
  if test $? -ne 0
  then
    echo "" 1>&2 
    echo "# ${MYNAME} : ERROR running dmcoords" 1>&2
    echo "" 1>&2 
    exit 1
  fi

  #
  # Save into a temporary file to use with dmimgpick
  #   The 3rd column is the output from dmimgpick; but we
  #   don't know the name of the input image block so we
  #   rename on the fly
  #
  pget dmcoords x y | tr -s "\012" " " > ${tmpdir}/$$_pos.dat
```

The intentional (and necessary) `punlearn` breaks other instances running at the same time, and by the time the `pget` happens, the values may have changed.   I know I hit this exact same thing with `arfcorr` which also has `dmcoords`-sensitivity 

[I didn't know if your scrips-that-don't-support `@@` logic also implicity solves this race condition by setting up a temporary PFILES.]

**Comment by kglotfelty** [comment]
From the original list: `evalpos`, `mean_energy_map` , `pileup_map`, and (surprisingly!) `wavdetect` are all using the `pquery` trick.   

But each are using individual tools in a what that makes them none-thread-safe.

**Comment by DougBurke** [comment]
For commands marked as "can-not-use-the @@ trick", runtool runs them with a
temporary parameter directory. Or at least it should!

**Comment by kglotfelty** [comment]
That's what I thought.  That may then be a good-enough reason to just treat all the shell scripts as @@-lacking.

**Comment by DougBurke** [comment]
I think the short-term approach is to release a version which makes the extra tools as having to be run directly (i.e. those in the list apart from dmgti and fullgarf) and then look at enhancing the `CIAOToolDirect` class so it is run with its own parameter file directory. The latter step needs significantly-more testing to validate!
