### ISSUE TITLE
dax: spectral model code call set_xschatter(0) 

### ISSUE THREAD

**Issue by DougBurke** [cxcsds/ciao-contrib#498]
In CIAO 4.14 the XSPEC models have got a little chattier, which can lead to extra output (eg #497). Thanks to the way stdout gets set, these messages may appear in the "standard" output or in the terminal which launched ds9 - @kglotfelty knows from

We could hide these messages by calling `sherpa.astro.ui.set_xschatter(0)` before creating any models, and preserve the pre-4.14 behavior.

We could keep the new chatter setting (of 10) since it can point out some odd cases (e.g. ATOMDB_VERSION setting in ~/.xspec/Xspec.init being old).

We could make it a settable value (defaulting to 0) so people can change it if they do find odd behavior.

We would get output from apec and TBabs - I forget the other models we use in dax but you can check in 4.13 with

```
sherpa In [1]: set_xschatter(10)

sherpa In [2]: xsapec.mdl([0.1, 0.2, 0.3], [0.2, 0.3, 0.4])
Reading APEC data from 3.0.9

Out[2]: array([2.10839183, 0.31196176, 0.22008776])

sherpa In [3]: xstbabs.mdl([0.1, 0.2, 0.3], [0.2, 0.3, 0.4])
tbvabs Version 2.3
Cosmic absorption with grains and H2, modified from
Wilms, Allen, & McCray, 2000, ApJ 542, 914-924
Questions: Joern Wilms
joern.wilms@sternwarte.uni-erlangen.de
joern.wilms@fau.de

http://pulsar.sternwarte.uni-erlangen.de/wilms/research/tbabs/

PLEASE NOTICE:
To get the model described by the above paper
you will also have to set the abundances:
   abund wilm

Note that this routine ignores the current cross section setting
as it always HAS to use the Verner cross sections as a baseline.
Out[3]: array([2.31580099e-154, 2.41182884e-026, 5.47727885e-010])
```

**Comment by kglotfelty** [comment]
I think it's probably best letting sherpa defaults rule this and just go with whatever the default is.  

I checked and the messages end up in the same "Spectral Fit" window as the rest of the sherpa textual output rather than the terminal where ds9 was launched so the info that is printed is in the context of what's happening.

I don't think it's worth adding a verbosity level setting as we don't do that for the other tasks.

**Comment by DougBurke** [comment]
I'm closing this but please holler @kglotfelty if it needs to be re-opened (we haven't had screams from the user community yet about it anyway, for whatever that's worth ;-)
