### ISSUE TITLE
mktgresp: problems w/ asphist cleanup in Python 3

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#50]
mktgresp uses `map()` to clean up the temporary aspect histogram output files. In Python3 this isn't working as expected; at least on osxElCap in CIAO 4.10b1.  This should be re-written to avoid the p2/p3-isms.

**Comment by DougBurke** [comment]
Is it a problem with the code not treating map as a generator, or more
subtle than that?

**Comment by kglotfelty** [comment]
I'm not sure if there is/isn't some kind of subtle garbage-collection/OS-specific timing kind of thing going on.  I don't see it in any of the P3 ciao-4.9 builds -- only on the ElCap P3 4.10b1 so far.

Basically it's doing a 

```python
try:
    stuff
finally:
    map(os.unlink, list_of_temp_filenames)
```

which, looking at it, shouldn't have worked in any of the P3 builds since the iterator returned by `map` was never explicitly used.   But it has been (or I would have gotten a can't clobber existing file message).

I just need to loop over the list explicitly.

**Comment by kglotfelty** [comment]
Files created myself

**Comment by DougBurke** [comment]
So I think you could just be explicit - e.g.

    for f in blah:
        moreblah(blah)

rather than hide the action in a `map`.

**Comment by kglotfelty** [comment]
👍
