### ISSUE TITLE
specextract response position 

### ISSUE THREAD

**Issue by nplee** [cxcsds/ciao-contrib#551]
I've been looking into how specextract currently determines the location where responses are generated if a `refcoord` position isn't provided.  An extreme example is looking at a large extended source:

![CasA-resp_pos](https://user-images.githubusercontent.com/23193862/142230011-0385d02d-7dc2-4770-968e-77b3991f935a.png)

The ellipse is the defined extraction region for Cas A and the magenta 'x' represents the maximum location found by `dmstat`, which is where specextract would presently use to generate an unweighted response.  The cyan mark represents the centroid location determined by `dmstat`, but it appears the reason why the the maximum was picked over the centroid is that dmstat could fail to locate a centroid, and in the past this would cause specextract to fail due to the problem corresponding to zero counts.

The yellow mark presents the calculated center from the extraction region's extent using `region.CXCRegion`, and it looks like the centroiding does a pretty decent job.

![moritz-resp_pos](https://user-images.githubusercontent.com/23193862/142242548-b69a2186-5b63-4171-9ecf-71dd0e18a70a.png)

But in the `arfcorr` issue reported last week, where the user is looking at 90% ECF regions, we see that the maximum and centroid location are identical, but the derived center (yellow) is quite different.  Using the centroid position for the ARF, the PSF_FRAC values are roughly 60% while the calculated center is the expected 90%.

So the question is, should the `dmstat` approach be abandoned in favor of the extent-derived location?

**Comment by DougBurke** [comment]
Something of an aside, but for extended sources we don't care about `arfcorr` (at least for very-extended; for slightly-extended there could still be a reason to include the `arfcorr` correction).

**Comment by kglotfelty** [comment]
FYI -- here is a notebook with a realistic example where we do care about the `arfcorr` correction.

https://nbviewer.org/urls/hea-www.harvard.edu/~kjg/Specextract_Position_Experiments.ipynb

**Comment by nplee** [comment]
The method I've come up with, but haven't pushed yet, is to use the centroid, and if it's within n pixels away from the center of the bounding box, it'd use that position for the responses, otherwise it would use the center of the bounding box.

But if using the center of the first region of a composite region is better, I can be convinced to revise the approach.

**Comment by DougBurke** [comment]
@nplee can we close this or do you want to leave it open?
