### ISSUE TITLE
dax apply blocking to saved image

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#570]
ds9 doesn't update the WCS when saving which is why dax needs to separately filter the save file to apply any cropping:

https://github.com/cxcsds/ciao-contrib/blob/151f7fc17bc4b3a2dd32513ebf930a3facdde461/bin/ds9_imgproc_wrapper#L184

This also applies to **blocking** (not binning nor zooming). If the image has been blocked the wcs isn't updated when the image is saved which causes coords to be off.  

dax can get the blocking factor same as w/ cropping and apply it to the data when creating the temp file so that things should work better.

**Comment by DougBurke** [comment]
Is this something we could ask DS9 to improve, or is it out-of-scope and so we will need to do it?

**Comment by kglotfelty** [comment]
From Bill:  

> Saving a new WCS in an existing file is a major can of worms. I’m passing for now.

It looks like we'll be able to do it in `dax`, but will require changes to the `wcs` `xpa` access point that will be released in ds9 8.5.  I'll revisit in the fall.
