### ISSUE TITLE
Review ploting code for updates of Sherpa

### ISSUE THREAD

**Issue by hamogu** [cxcsds/ciao-contrib#580]
There are a number of places where sherpa plotting is used, in particular in "bin" but also in sherpa/contrib. In some cases, the chips backend is still special-cased.

I have not looked at all of them in detail, but just at a few examples and it seems that the vast majority can be made backend independent by just replacing `from sherpa.plot import backend` with `from sherpa import plot` and then use `plot.backend` in the code. 

There are a few other cases that are worth touching, e.g. chips support can be remove. When my sherpa plotting re-work is a little further along, I will address those.

Question: Does this need to be backwards compatible? If so how far back? Or is it sufficient to work with the current sherpa main branch? 

Those cases that I've looked at are probably backwards compatible but it might be cleaner if that is not required, i.e. we release ciao-contrib with a new sherpa release.

**Comment by hamogu** [comment]
Need to look in more detail at

- Any file that mentions "chips" (just grep). If chips special-cased, there sure are others
- Any file that mentions "pylab"  (just grep). If pylab special-cased, there sure are others
- `sherpa_contrib/profiles/annotations.py` re-implements the sherpa logic of selecting a backend and loading it, `sherpa_contrib/profiles/annotations_pylab.py` should just be moved into sherpa itself.
- There a A LOT of xml files that mention chips explicitly. Might be a good time to clean that up as well.

**Comment by DougBurke** [comment]
Argh: I thought I'd got the changes for CIAO 4.15 but I missed the sherpa_contrib/profiles changes....

**Comment by DougBurke** [comment]
@hamogu - although a lot of ahelp files that mention chips

a) many are is chip as in ACIS chip
b) the ones that refer to ChIPS are actually all commented out (should remove them but ...)

I've only found one file that mentions chips. I've just pushed a change for all this, so please let us know if you see some text that still talks about chips (I have kept in "changelog" comments that refer to chips).

**Comment by hamogu** [comment]
@DougBurke Great. Thanks. I saw it somewhere when I opened this issue, but I believe that you've gotten them all; I think we can close this and if I see it again, I'll open a PR.
