### ISSUE TITLE
RFE: Support OBC mode

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#59]
Following from #47 :  various scripts will need to be updated to support OBC mode datasets.

First we should get our docs in order -- probably needs a new thread for how to process, including the ability to change GTIs so that we get non-zero good-time at L2.  Otherwise it's somewhat straight forward, though invasive -- we need to look for the stack of `*_osol1.fits` files in the `secondary/aspect` directory instead of in the `primary` dir.  

We can trigger off the `ASPTYPE` keywords in the evt1 file so there is a path, just will affect any tool that is looking for the aspect solution.

**Comment by kglotfelty** [comment]
# fluximage

An unexpected twist ...

Because the `*_osol1.fits` files are not cut on obsid boundaries, they can cover a large part of the sky (many degrees).

The asol object used by `fluximage` computes the number of aspect histogram bins (`asphist.max_bin`)  from the min/max ra/dec/roll.  For obsid 2469 this comes out to be over 68 billion bins, which causes `asphist` to SEGV.  

Trying to run `asphist` by hand using the default max_bin parameter things don't look right (`x_offset` and `y_offset` values in the 1000's) .

If I pre-filter the `osol` file by the obsid's  `TSTART`/`TSTOP` then the aspect histogram looks more reasonable.

**Comment by DougBurke** [comment]
I seem to remember doing a time-based filter on the asol files being passed
to the aspect histograms (using the event file GTI to handle cases where
people may have done some "fun" time filters). So maybe we use the same
approach here?

Doug

**Comment by kglotfelty** [comment]
We'd only want to limit it to the start/stop time ranges (or say min/max times in the event file); not actually filter the asol/osol by the evt's GTIs.  

There are 'partial bin' kinds of issues that `asphist` works out when the GTI cuts an asol record but it needs to have all the asol records to do it.   [We saw this with observations with lots of dropped exposures (many GTIs) which messed up the ARF when we originally told users to GTI-filter the asol files.] 

It probably does not matter for these obc datasets ... just something to be careful 'bout if it's done is a generic kind of way.
