### ISSUE TITLE
dax sherpa spectral fitting - add model flux

### ISSUE THREAD

**Issue by anetasie** [cxcsds/ciao-contrib#600]
Not sure if this is on the list for the additional `dax` features. I would like to add flux calculations using `sample_energy_flux`, which could be included as additional button in the DAX Model Editor with return of the flux value and the distributions.

**Comment by DougBurke** [comment]
Given that we have `sample_flux`, `sample_energy_flux`, and `sample_photon_flux` we should identify what we actually want done first before looking at adding this to dax.

**Comment by kglotfelty** [comment]
`dax` already reports the flux using `calc_energy_flux` and `calc_photon_flux` after the fit is complete and user presses `Continue` .  This shouldn't be an option part of the model parameter editor .
