### ISSUE TITLE
dax - add chart output to Sherpa fit

### ISSUE THREAD

**Issue by anetasie** [cxcsds/ciao-contrib#601]
It would be nice to add the option to write output of the model in the `chart` format, ready for input to the CHART simulations.
Perhaps this is already on the list of additional features, but I just really wanted to have that option now.

**Comment by DougBurke** [comment]
We do have a contrib routine to write out chart data, but I haven't looked at them for a long time and don't know it it still works. 

https://cxc.cfa.harvard.edu/sherpa/ahelp/save_chart_spectrum.html

**Comment by anetasie** [comment]
Yes, the contrib routine works in Sherpa. It would be nice to include it as an option in  DAX

**Comment by kglotfelty** [comment]
It sounds like this and #600 are really less about dax ... and more about wanting a sherpa gui? That's a reasonable thing, but I worry about trying to just haphazardly add buttons to dax -- it's supposed to be simple for most things, not comprehensive.
