### ISSUE TITLE
specextract warning with warm FP temps (placeholder)

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#624]
From meeting w/ MP, cycle 24 targets will be taken at warmer temps where the current calibration is less accurate.  There is a desire to inform users with high SNR data (specifically line centroids which may shift, continuum less affected) about this uncertainty.  We'll be adding a blurb to threads, but since users who already know how to extract spectra don't read threads again, the feeling is that we should provide a warning when spectrum are extracted.

Details are TBD, and text of any such warning will require high-level editorial approval.  But we do know that only the FP_TEMP value taken from header is sufficient, we don't need to lookup range of FP_TEMP values eg in mission time line file.

The desire is to have this in place for 4.15 commensurate w/ the start of cycle24 observations.  I expect we'll discuss more at next scripts meeting.

**Comment by nplee** [comment]
Thanks for the heads up.  There is a FP_TEMP check for >-110C observations already, so pending further details and editorializing, this should be easy to include.

**Comment by kglotfelty** [comment]
Below is the current draft of the new warning that has been OK'd by CAL et al.  It still may get tweaked, but this should be the last thing printed:

```
    Caution:

    The mean ACIS focal plane temperature for this observations is ${FP_TEMP} C
    which is warmer than the currently calibrated high temperature limit
    of -109 C (164.15 K). 

    Users fitting ACIS imaging spectra that fulfill all the following three conditions 
    may see line-centroids shifted by 1-2% from systematic offsets due to calibration uncertainty:

    (1) Spectra with more than 1000 counts on a front-illuminated (FI) chip or more 
          than 2000 counts on a back-illuminated (BI) chip (CCD_ID 5,7).

    (2) More than half of source counts were acquired above the current temperature 
         limit of -109 C.

    (3) More than half of source counts are in emission or absorption lines.

    Under these conditions, users may benefit from trying to identify time periods when the 
     focal plane temperature was within the currently calibrated range, below -109C, 
     using the following thread:

    https://cxc.cfa.harvard.edu/ciao/threads/acisfptemp/

```

where `${FP_TEMP}` is the `FP_TEMP` keyword converted from K to C.

**Comment by DougBurke** [comment]
We can close this now I think?

**Comment by DougBurke** [comment]
I'm closing this. Please re-open if needed.
