### ISSUE TITLE
chandra_repro work around dm @ filter bug

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#638]
There's a bug in `dmcopy` when applying a mutli-component GTI filter, ie a `flt1` file, in conjunction with other filters -- only the 1st component, ie `ccd_id` is used, so the rest of the chips are filtered-out.

This

https://github.com/cxcsds/ciao-contrib/blob/41defab8d2f4f8c41ff115aed63921fc487c6d1d/bin/chandra_repro#L1840-L1842

Needs to be broken up into two commands:  one to do the grade/status filter (first, quicker) and then the `flt` part.

**Comment by DougBurke** [comment]
I know there are other recent changes to improve the handling of `@filters` but is it just safest to always break any filter that uses one into two separate steps?
