### ISSUE TITLE
cannot use acis_clear_status_bits (and some others) from runtool

### ISSUE THREAD

**Issue by hamogu** [cxcsds/ciao-contrib#643]
A co-worker reported the following problem to me:

I like scripting things from Python, e.g. downloading data goes through `ciao_contrib.cda`, while most tool go through `runtool`. Where is `acis_clear_status_bits`?

After some investigation, I think I can say that `acis_clear_status_bits` is nowhere - it can only be called with `subprocess.call`, not with `runtool`. That's not a big problem in principle (since runtool is just a fancy way of building up the parameter file and then calling the CIAO tool), but it's a problem of discoverability: It's hard to find where things are.

I had, naively, expected to find `acis_clear_status_bits` in runtool, since it has the same flavor as many other contributed scripts, but it's not there, because it does not use a parameter file, instead it's directly reading from `sys.argv`: https://github.com/cxcsds/ciao-contrib/blob/151f7fc17bc4b3a2dd32513ebf930a3facdde461/bin/acis_clear_status_bits#L104
Thus, it's not made into a runtool, which is build by parsing the .par files.

I see three possible solutions:

- Do nothing. No par file wrangling needed, let users call `subprocess.call` directly. I think this is not ideal because of discoverability.
- Add a .par file for `acis_clear_status_bits`. That's backwards compatible because it only has one parameter that is passed in the command line. One would still do that even if it has a par file.
- Add a new category to the existing `CIAOToolDirect` and `CIAOTollParFile` classes, called `CIAOToolNoParFile`.

I note that there are some other tools that are not available in runtool, e.g. `check_ciao_version`. 

The following code lists a number of missing tools:
```Python
import os
from glob import glob
from ciao_contrib import runtool as rt

rttools = set(rt.list_tools())
binlist = set([os.path.basename(f) for f in glob(os.environ['ASCDS_CONTRIB' + '/*')])

binlist - rttools
```
lists

{'acis_clear_status_bits',
 'check_ciao_caldb',
 'check_ciao_version',
 'convert_xspec_script',
 'convert_xspec_user_model',
 'download_chandra_obsid',
 'ds9_aper.sh',
 'ds9_functs',
 'ds9_imgfit.sh',
 'ds9_imgproc_wrapper',
 'ds9_lut',
 'ds9_plot_blt',
 'ds9_radial_fit',
 'ds9_snap2.sh',
 'ds9_specfit.sh',
 'ds9_tgcoord.sh',
 'install_marx',
 'splitroi',
 'summarize_status_bits',
 'tg_bkg

Of those, I would argue that acis_clear_status_bits, splitroi, summarize_status_bits, and tg_bkg should be available in runtool in some form, possibly also the check_* and download_chandra_obsid.

**Comment by DougBurke** [comment]
So, the parameter file has good and bad points, including but not-limited to

- it provides a machine-readable specification of the supported parameters/arguments to a tool
- it is awkward to handle when running scripts in parallel
- it is awkward to set up the parameter-file location (both the "pristine" version and the user version)
- it is possible to corrupt the parameter file which then causes no-end of problems

The runtool module is based on the first assertion I made - that we have a machine-readable way of specifying the parameters. Without this, tracking changes to scripts is very hard and can potentially break things (e.g. when the script changes but the runtool interface doesn't).

There's also the fact that the parameter-file interface doesn't really map well to the argparse interface (at least as I tend to write them). The runtool interface would have to be taught how to call optional parameters, and then work out how to handle partially-specified parameters.

None of this is hard, but it would add more complexity to the code (and it's surprisingly complex enough as is) and I'm personally not sure it's worth it, given that they can use subprocess to run the non-parameter tools. However, I am rather biased here.

I thought I had more text about this in either

 - https://cxc.cfa.harvard.edu/ciao/scripting/runtool.html
 - https://cxc.cfa.harvard.edu/ciao/ahelp/ciao_runtool.html

but I think it's mainly in the docstring - i.e. you'd need to

>>> from ciao_contrib import runtool
>>> help(runtiol)

to see it. I think the documentation [*] is written with the assumption of "it's obviously only for tools with a parameter file", so it probably doesn't spell it out quite enough for users like the aggrieved co-worker, to help them out.

[*] as author of said documentation

**Comment by hamogu** [comment]
I wonder if it makes sense to add the four tools I mentioned above so that, when called, it would say something like:
```
NotImplementedError('Tool XXX does not use a parameter file and is thus not wrapped by runtool.
 Call it with subprocess.call(XXX, parameters) instead, see YYY for an example')
```

where YYY could be link to the Python documentation or a thread on the CIAO page.  That's (a) easy to do and (b) not a maintenance burden since it's only an informational message - it won't break even if the CIAO tool changes. In the worst case, we don't update the list of tools that display this message - and then we are exactly where we are now. Coming to think of it, I should probably just make a PR so that we have a specific proposal to discuss.

I personally have a dislike for parameter files and would love to get rid of them for all tools, but alas, I think that ship has sailed about 25 years ago.

**Comment by DougBurke** [comment]
@hamogu - what about marx? Should we extend #649 to complain about marx too?

**Comment by hamogu** [comment]
Marx does in fact use a parameter file interface,  so that's a different case and beyond the scope of this pr
