### ISSUE TITLE
dax cancel button leads to ugly traceback

### ISSUE THREAD

**Issue by DougBurke** [cxcsds/ciao-contrib#659]
In a spectral fit via dax I hit the cancel button and got the following dumped into the log window - it seems a bit excessive

```
Traceback (most recent call last):
  File "/tmp/ds9_dax.dburke/specfit/105b624825c12c1192c488e1df938b41/cmd", line 45, in <module>
    DaxModelEditor(mdls, "ds9").run(sherpa.fit,sherpa.conf)
  File "/home/dburke/miniconda3/envs/ciao414-contrib/lib/python3.9/site-packages/dax/dax_model_editor.py", line 171, in run
    raise DaxCancel("Cancel Button Pressed")
dax.dax_model_editor.DaxCancel: Cancel Button Pressed
```

**Comment by DougBurke** [comment]
Also, if I don't cancel this particular window then it remains even when I exit ds9. Which was surprising to me. I don't know if we (well, you) can know whether to kill this process/whatever when ds9 exits.

**Comment by kglotfelty** [comment]
w.r.t. the exception: I can probably catch the `DaxCancel` exception in the script it generates .

w.r.t. closing ds9 -- there's nothing much we can do if ds9 closes while the script is running (without spawning some other process to check for a ds9 heartbeat (`xpaget ds9 version` or some such).  

> Technical note:  the dax model editor is using Python's TK, not ds9's (which is why there are visual diffs), esp conda which doesn't support smooth fonts.
