### ISSUE TITLE
dax and new scripts

### ISSUE THREAD

**Issue by DougBurke** [cxcsds/ciao-contrib#664]
Do we want to add psf_contour and mk_bg_region_with_set_number_fo_counts_with_a_really_intuitive_name to dax?

i just tried creating a region for specextract testing and would have liked a way to select a point and have it create a source and background region appropriate for that position (e.g. to some given ECF and some scaling for the background size) [*]. Is this possible to daxify? Do we already have it and I'm just too old-skool to know the deets?

[*] it starts to get more complex if we already have regions shown, since would you then want to ensure they are excluded from the calculated regions, but I think I'm over-complicatering it

**Comment by kglotfelty** [comment]
I hadn't thought about it, but yes they can be added to dax.

The way it will work is that dax will use the center of the regions (select if any, if none selected then all ... circles, ellipse, and boxes only) and use the coordinates of the center as the position.

I've tried making users go into crosshair mode ... they don't ... it just confused users.  

It could be bound to a key press -- but **nobody** is going to read the docs to know what key to press.

Not sure it'll make 4.15 at this point.

**Comment by kglotfelty** [comment]
closed by #673
