### ISSUE TITLE
specextract ahelp context

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#691]
I don't think we need to fix this for 4.15, but it looks like the change to the `specextract` ahelp file got lost in the updates.

https://github.com/cxcsds/ciao-contrib/blob/d2dea6c3cc33b79fc196933d83dff6f944503fc8/share/doc/xml/specextract.xml#L6

It should be

```
context="Tools::Composite"
```

**Comment by nplee** [comment]
I haven't passed off the tarball to CM yet, if that makes a difference.

**Comment by DougBurke** [comment]
Make a quick PR and I'll merge it ;-)
