### ISSUE TITLE
srcflux replace load_module

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#706]
the new plugin code is using the deprecated `importlib.load_module` method 

https://github.com/cxcsds/ciao-contrib/blob/4c43b6fe4bdb768ece34b388db7d907fbe01297e/bin/srcflux#L3041

will eventually need to replace.

**Comment by DougBurke** [comment]
The replacement should be easy (I forget now but we've done it in sherpa)
