### ISSUE TITLE
simulate_psf: PSF image size

### ISSUE THREAD

**Issue by nplee** [cxcsds/ciao-contrib#72]
Kenny,

Looking into a helpdesk ticket where the PSF image of a gratings observations is outputting HUGE (16k x 16k) images of the entire field and dispersed spectrum, ignoring the "minsize" parameter.  According to the ahelp, if the "minsize" parameter is set, then "numsig" is ignored, but this doesn't seem to be the case.  In the get_xygrid function:

```
    #
    # Use sky pixel of ra,dec as center
    #
    xx = int(float(src_info["x"])+0.5)+0.5
    yy = int(float(src_info["y"])+0.5)+0.5
    
    sigs = [float(r) for r in dmstat.out_sigma.split(",")]
    xlen = int(float(pars["numsig"]) * int(sigs[0] + 1)+0.5)
    ylen = int(float(pars["numsig"]) * int(sigs[1] + 1)+0.5)
    mlen = max(xlen, ylen)  # let's make square images, people like those

    if "INDEF" != pars["minsize"]:
        mm = int(int( pars["minsize"] ) / 2.0 )
        mlen = max( mlen, mm )
```

we see that mlen can still be dependent on "numsig", unless the conditional is changed to:

```
    if "INDEF" != pars["minsize"]:
        mlen = int(int( pars["minsize"] ) / 2.0 )
```

**Comment by kglotfelty** [comment]
This is closed with #89
