### ISSUE TITLE
specextract use make_tool instead of importing global instance

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#730]
We should look at replacing the import of individual tools 

https://github.com/cxcsds/ciao-contrib/blob/26981f49107088a7c3d58eb12a95f23e33685bfe/ciao_contrib/_tools/specextract.py#L31

with using `make_tool` in the places where they are used.  

```python
from ciao_contrib.runtool import make_tool
dmstat = make_tool("dmstat")
```
This is especially important for `dmstat` which is storing info back into it's own parameter file and especially when running in parallel.  Since this is imported into the global scope, all the paralell threads are updating the same object.  If you create separate objects for each parallel thread then no race condition.

This should help remove the need for so many `new_pfiles_environemnt` contexts.

**Comment by DougBurke** [comment]
@nplee does #736 close this issue, or is it worth keeping open?

**Comment by nplee** [comment]
@DougBurke this closes it 👍
