### ISSUE TITLE
srcflux requires same tangent point when user supplies regions

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#738]
When users are combining multiple observation and use their own regions, ie set `srcreg` and `bkgreg` parameters then

- The regions must be in celestial coordinates 
- The event files must be reprojected to the same tangent plane

`srcflux` assumes this to be case and produces bogus results if it's not.    Need to look into adding checks to enforce these conditions.
The tangent plane should be sufficient to check `_NOM` keywords.  The regions are a different story since there is no existing programmatic way to robustly determine regions coordinate system.

**Comment by DougBurke** [comment]
One hacky thing would be to try something along the lines of

- filter an event file
- compare the bounds of the region to the subspace

since at least for sky coordinates you are often outside a sensible ra / dec range. But you could drive a bus through the holes in  this strategy...
