### ISSUE TITLE
srcflux use new psfsize_srcs and bkg_fixed_counts

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#785]
Add an option to srcflux to use the new (in 4.15) psfsize_srcs and the bkg_fixed_counts scripts to create the source and background regions.   

psfsize_srcs **requires** that `marx` be installed so we need to decide if this is the new default or keep current ECF based regions w/ `marx optional.

**Comment by DougBurke** [comment]
I assume this can get closed now, or is there still a question of the default behaviour?

**Comment by kglotfelty** [comment]
default is good.  closing.
