### ISSUE TITLE
chandra_repro replace home-grown history

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#8]
chandra_repro uses it's own `add_history` routine instead of the `ciao_contrib.runtool.add_tool_history` routine.  (ie calls dmhistory with it's own local .par file)

We should update it to use the common lib which doesn't have a problem when the `outdir` is the same as `PFILES` (there's a shutil's copy that throws a can't-copy-because-infile-is-same-as-outfile  exception.)

**Comment by DougBurke** [comment]
Is there any functionality in the `chandra_repro` version that needs to be
added to `add_tool_history`?

**Comment by kglotfelty** [comment]
Nope, it's just iterating over a few files  ... Should be almost entirely plugin 

Kenny
