### ISSUE TITLE
Fix python version in README_CIAO_scripts

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#837]
https://github.com/cxcsds/ciao-contrib/blob/5337f58e92d03ed08def492489d6e6d22f02eacc/README_CIAO_scripts#L35

**Comment by DougBurke** [comment]
Also the fact that it isn't in `/contrib`. 

In fact 90% (*) of the document isn't relevant anymore....

(*) this may be a made-up statistic found on the internet

**Comment by DougBurke** [comment]
I think we just delete this file completely. Any argument to this @nplee ?

**Comment by DougBurke** [comment]
Fixed by 
- #838
