### ISSUE TITLE
make_version_file looking for contrib dir

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#847]
https://github.com/cxcsds/ciao-contrib/blob/eaba8ccfe4c00a7b7387e826245ce7d5fd5c7443/make_versions_file#L75

need to update to look in $ASCDS_INSTALL

**Comment by DougBurke** [comment]
I've just added a commit to address this (forgot to make it a PR)

https://github.com/cxcsds/ciao-contrib/commit/a83799bb9b9bf5d223c95ae18f764950d17c1386
