### ISSUE TITLE
allow catalog=latest for search_csc / obsid_search_csc?

### ISSUE THREAD

**Issue by DougBurke** [cxcsds/ciao-contrib#850]
Using catalog=latest would mean the calls are made with no catalog version, which will then return the latest finalised version (so it's not the same as the current catalog=current).

It saves uses from caring about what catalog setting to use for people who just want the latest-and-greatest...

**Comment by kglotfelty** [comment]
Is there a way to know what release `latest` actually is?

**Comment by DougBurke** [comment]
I don't believe so (we could identify the latest ascds-release value,  or
whatever the column is,  but that doesn't tell us anything that useful)

**Comment by kglotfelty** [comment]
Humm ... that concerns me.  In the short transition time between when 2.1 is released and when we release the updated code to allow the specific "2.1" option -- I'd rather see users continue to use 'current' or continue to use the 2.0 release.  At least with current all bets are off (no idea if columns, joins, data products, etc) are correct whereas the actual releases are correct (for that specific release).
