### ISSUE TITLE
Install ciao-contrib

### ISSUE THREAD

**Issue by alisson26** [cxcsds/ciao-contrib#854]
Hi guys, someone can helpe me on how tow install ciao-contrib module in python ? I need it to run Ciao from miniconda env. 

Thanks in advanced for some help in this question. 

Best

**Comment by nplee** [comment]
@alisson26 please contact the Chandra helpdesk (https://cxc.cfa.harvard.edu/help/) since contrib module should be a part of a standard CIAO installation (https://cxc.cfa.harvard.edu/ciao/download/conda.html).
