### ISSUE TITLE
parse_pos problem with strings in files

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#868]
Re: helpdesk ticket 25220

There is a disconnect in the parse_pos routines when parsing a single string vs a file that contains strings for ra & dec column (ie in HMS format)

https://github.com/cxcsds/ciao-contrib/blob/de8e6c146c2741d023ecd205ad63595fcae483f7/ciao_contrib/parse_pos.py#L71

The `_str` routine returns a list, but the `_file` needs to treat it like a scalar value.  Need to review/rework the logic so that both a single "ra dec" string works as well as file w/ "ra dec" strings.

**Comment by DougBurke** [comment]
I'm assuming this is not a stop-the-presses type situation?

**Comment by kglotfelty** [comment]
I don't think so.  It's been that way for a long, long time and there's a work-around (use prop_precess to convert to degree; a few hoops to jump through but not bad).  Fix should be simple, but not a today kind of thing -- just want to be careful and double check other usage.
