### ISSUE TITLE
q: can I get the redirected value of a parameter?

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#871]
If I

```python
from ciao_contrib.runtool import make_tool
ape = make_tool("acis_process_events")
print(ape.eventdef)
```

I get

`)stdevt1`

Is there a nice way to get the actual value, ie `'{d:time,l:expno,s:ccd_id...}'` instead of the redirect or do I have to parse the value looking for `.startswith(')')`

**Comment by DougBurke** [comment]
I'd have to look through the code, but I think I got to this point and punted on the definition of "what a value is" (is it the value, is it the redirect, is it both ...).
