### ISSUE TITLE
aplimits with sherpa 4.16.1

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#880]
With the sherpa 4.16.1 changes that came into CIAOX this week we are getting a failure in the `aplimits` script:

```diff
> Traceback (most recent call last):
>   File "INSTALL/bin/aplimits", line 54, in <module>
>     from sherpa.utils import igam, lgam, bisection
> ImportError: cannot import name 'bisection' from 'sherpa.utils' (INSTALL/lib/python3.11/site-packages/sherpa/utils/__init__.py)
```

**Comment by DougBurke** [comment]
I htink we can just take the bisection code that was removed in https://github.com/sherpa/sherpa/pull/2015 and add it to the the script.

Unless we start finding it used elsewhere.

**Comment by DougBurke** [comment]
For reference, this is the commit we care about: https://github.com/sherpa/sherpa/pull/2015/commits/60ee61a115f4820e03b7264f4035a0d43f38d198

**Comment by kglotfelty** [comment]
The only other place I can think that might be using it would be the level3 stuff; but not sure where that code lives.

**Comment by kglotfelty** [comment]
closing since sherpa reverted change.
