### ISSUE TITLE
download_obsid_caldb locate evt w/ filters

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#90]
`download_obsid_caldb` is using `os.path` routines when looking for the event file which fails when the infile has a filter.

I should check to see if Doug's already got a more robust version of this and/or add some hooks to strip|split the filters off before checking file names.

**Comment by DougBurke** [comment]
I do have some hacky code to do this, but it's not guaranteed to be robust.
It probably makes sense to try and centralize this logic somewhere
"official" though.
