### ISSUE TITLE
specextract weighted ARF 0 counts

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#903]
(Sorry, not sure if this is already a different issue -- if so feel free to close this one.)

Looking through helpdesk tickets there have been a lot of recent issues where `specextract` users have 0 counts in the source o background using the default energy range which triggers a `FileNotFoundError` exception (`sky2tdet` fails). 

We should look to see if we can catch this case and provide a more useful message/feedback to suggest either try a different region, try a different energy band, or both.

**Comment by nplee** [comment]
This should be caught in `ciao_contrib/_tools/specextract.py` revised in PR #870 that made it into the contrib 4.16.2

**Comment by kglotfelty** [comment]
**GREAT**

We should update the scripts' version history page to include it.

**Comment by nplee** [comment]
ugh... how'd I completely miss adding an entry while updating the page when I'm also the one that made the change. 
::facepalm::
