### ISSUE TITLE
dax spectral models?

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#905]
I noticed in the `dax` regression test the blurb about `xswabs` being deprecated.  We haven't update the list of spectral models available with `dax` in a while.  Are there any we should consider adding/removing?

**Comment by DougBurke** [comment]
Well, xswabs is I think going to stay around, it is just not something that it's worth using as it's outdated.

I can't think of any others in terms of deprecation.

What is the current list of models that dax knows about?

**Comment by kglotfelty** [comment]
For spectral models:

```
model menu {Model: mdl1} powlaw1d|bbody|bpl1d|gauss1d|normgauss1d|lorentz1d|logparabola|xszpowerlw|xszbbody|xsbknpower|xscutoffpl|xszgauss|xsdiskline|xsapec|xsbapec|xsmekal|xsvmekal|xsraymond|xszbremss|xscemekl {Spectral Model - model editor will open}
add_model menu {Additional component: mdl2} none|powlaw1d|bbody|bpl1d|gauss1d|normgauss1d|lorentz1d|logparabola|xszpowerlw|xszbbody|xsbknpower|xscutoffpl|xszgauss|xsdiskline|xsapec|xsbapec|xsmekal|xsvmekal|xsraymond|xszbremss|xscemekl {Added to mdl1 - model editor will open}
```

For absorptions models:

```
specfit_absmodel menu {Absorption model: abs1} xsphabs|xswabs|xstbabs|xszwabs|xszphabs|xsztbabs {Absorption model - model editor will open}
specfit_absxtra menu {2nd Absorption model: abs2} none|xsphabs|xswabs|xstbabs|xszwabs|xszphabs|xsztbabs {Absorption model - model editor will open}
```

Just for completeness

For spatial models 

```
img_mdl1 menu {Model 1} gauss2d|beta2d|devaucouleurs2d|lorentz2d|const2d|polynom2d|sigmagauss2d|sersic2d|scale2d|normgauss2d {First model component}
img_mdl2 menu {Model 2} const2d|none|polynom2d|gauss2d|beta2d|devaucouleurs2d|lorentz2d|sigmagauss2d|sersic2d|scale2d|normgauss2d {Second model component}
```

and for radial profiles

```
rprof_srcA menu {Model1} gauss1d|beta1d|const1d|lorentz1d|polynom1d|powlaw1d {First model component}
rprof_srcB menu {Model2} none|gauss1d|beta1d|const1d|lorentz1d|polynom1d|powlaw1d {2nd additive model component}
```

**Comment by anetasie** [comment]
I agree with Doug. We can keep the `xswabs` for completeness. The default `dax` setting shows `xsphabs` which is fine.

The list of models looks good. I'm wondering about the statistics setting for 2d image fitting -  preferentially for X-ray images in counts we should have a default stat set to `cstat`.

**Comment by kglotfelty** [comment]
We don't know if user is fitting X-ray images or other images (radio, optical, etc). I presume the same reason why sherpa's default statistic is also `chi2gehrels`.
