### ISSUE TITLE
chandra_repro update the CALDBVER keyword

### ISSUE THREAD

**Issue by anetasie** [cxcsds/ciao-contrib#907]
I was checking the CALDBVER for the version of the processing and was seeing the original version for processing the file.
Of course I could just `grep CALDB` which would return other versions, but I'm wondering if we could update the keywords
to reflect the version which was used. Now, I'm also wondering if the gain files used in the chandra_repro were the most recent ones.

```
dmlist acis_repro_evt2.fits header | grep CALDBVER 
0143 CALDBVER             4.9.6                          String       
 --  HISTORY               PARM  :key=CALDBVER                                            ASC00458
```

```
- COMMENT chandra_repro was run with CALDB 4.11.2
```

**Comment by DougBurke** [comment]
So, there's a long philosophy about that should happen to the `CALDBVER` keyword.

I believe the feeling is, and @kglotfelty can correct me where I'm wrong, is that we can never guarantee that we can give a sensible value here so it's safer not to. Now, I do wonder whether this is true for the"specialized" case that is `chandra_repro`, but I'm willing to bet there's a reason.

**Comment by kglotfelty** [comment]
What @DougBurke said.  Even with all `chandra_repro` values set to defaults, there will still be calibrations that are not updated (things like recomputing aspect solution, good time intervals, mission timeline, etc.). The `CALDBVER` keyword is much less useful than the `*FILE` keywords.
