### ISSUE TITLE
download_obsid_caldb update for temperature dependent p2_resp files

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#920]
Need to figure out logic being used with multiple p2_resp files 

https://github.com/cxcsds/ciao-contrib/blob/3441cc58e5a87a7640da1b48b0fb60f5f89343ef/bin/download_obsid_caldb#L466

The script will just retrieve all p2_resp files matching the date rather than say taking in MTL file and figuring out which FP_TEMP values to cherry-pick.

**Comment by DougBurke** [comment]
I assume these are going to be large files, so the user benefits from the cherry picking.

**Comment by kglotfelty** [comment]
Assuming new files are about the same size as current ... current p2_resp is ~8Mb and I haven't paid attention to the details but there will be something like 6 FP_TEMP ranges .  So there is some advantage to cherry-picking but compared to 300Mb total for typical no-background CALDB, it's not a big deal.

Caveat: I need to double check if this is just the p2_resp files or if there will also be gain files (I don't think so).
