### ISSUE TITLE
Migrate scripts to new region module

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#96]
CIAO 4.10 includes the rewrite of the region module.  The scripts should be updated to take advantage.
From what I can tell, the following are candidates:

- [ ] `splitroi`
- [x] `src_psffrac`
- [x] `srcflux`
- [X ] ~`reg2tgmask`~
- [X ] ~`ciao_contrib.region.check_fov`~

The old interface is still functional in 4.10 but should be considered deprecated (methinks).

**Comment by kglotfelty** [comment]
n/a for `reg2tgmask` which needs ds9 format including special `tag`s.

**Comment by DougBurke** [comment]
So, `ciao_contrib.region.check_fov` doesn't parse the FOV file as a region - it manually decodes the structure. I'm not sure using the new region module would help in this particular case.
